export declare const MapOpsTypes: {
    create: import("../..").OperationTypes<never, never, never>;
    get: import("../..").OperationTypes<"map" | "key", never, never>;
    set: import("../..").OperationTypes<"value" | "map" | "key", any, "existingValue">;
    has: import("../..").OperationTypes<"map" | "key", never, never>;
    delete: import("../..").OperationTypes<"map" | "key", never, never>;
    keys: import("../..").OperationTypes<"map", never, never>;
    values: import("../..").OperationTypes<"map", never, never>;
    entries: import("../..").OperationTypes<"map", never, never>;
    clear: import("../..").OperationTypes<"map", never, never>;
    count: import("../..").OperationTypes<"map", never, never>;
    cmp: import("../..").OperationTypes<"value" | "test" | "compare", any, "value" | "test" | "key">;
    copy: import("../..").OperationTypes<"map", "deepCopy" | "deepCopyKey", "value" | "map" | "key">;
    map: import("../..").OperationTypes<"map", "transform" | "transformKey", "value" | "map" | "key">;
    toPlainObject: import("../..").OperationTypes<"map", never, never>;
    isValid: import("../..").OperationTypes<"value", never, never>;
    isEqual: import("../..").OperationTypes<"value" | "test" | "isEqual", any, "value" | "test" | "key">;
    isNotEqual: import("../..").OperationTypes<"value" | "test" | "isEqual", any, "value" | "test" | "key">;
    isLess: import("../..").OperationTypes<"value" | "test" | "compare", any, "value" | "test" | "key">;
    isLessOrEqual: import("../..").OperationTypes<"value" | "test" | "compare", any, "value" | "test" | "key">;
    isGreater: import("../..").OperationTypes<"value" | "test" | "compare", any, "value" | "test" | "key">;
    isGreaterOrEqual: import("../..").OperationTypes<"value" | "test" | "compare", any, "value" | "test" | "key">;
    asAny: import("../..").OperationTypes<"value", never, never>;
    asBoolean: import("../..").OperationTypes<"value", never, never>;
    asDate: import("../..").OperationTypes<"value", never, never>;
    asList: import("../..").OperationTypes<"value", never, never>;
    asMap: import("../..").OperationTypes<"value", never, never>;
    asNumber: import("../..").OperationTypes<"value", never, never>;
    asObject: import("../..").OperationTypes<"value", never, never>;
    asText: import("../..").OperationTypes<"value", never, never>;
    asTuple: import("../..").OperationTypes<"value", never, never>;
};
