
export const ID = {
  Entity: '@',
  Any: 'any',
  Boolean: 'bool',
  Color: 'color',
  Date: 'date',
  Enum: 'enum',
  Function: 'func',
  List: 'list',
  Many: 'many',
  Not: 'not',
  Map: 'map',
  Null: 'null',
  Number: 'num',
  Object: 'obj',
  Optional: '?',
  Relation: 'rel',
  Set: 'set',
  Text: 'text',
  Tuple: 'tuple',
  Delimiter: ':',
};
