import { Operations } from '../Operation';
export declare const BooleanOperations: Operations;
export declare const BooleanOps: {
    create: import("../Operation").Operation<never, never, never, never, never>;
    and: import("../Operation").Operation<"a" | "b", never, never, never, never>;
    or: import("../Operation").Operation<"a" | "b", never, never, never, never>;
    xor: import("../Operation").Operation<"a" | "b", never, never, never, never>;
    not: import("../Operation").Operation<"a", never, never, never, never>;
    cmp: import("../Operation").Operation<"value" | "test", never, never, never, never>;
    isValid: import("../Operation").Operation<"value", never, never, never, never>;
    isTrue: import("../Operation").Operation<"value", never, never, never, never>;
    isFalse: import("../Operation").Operation<"value", never, never, never, never>;
    asAny: import("../Operation").Operation<"value", never, never, never, never>;
    asBoolean: import("../Operation").Operation<"value", never, never, never, never>;
    asDate: import("../Operation").Operation<"value", never, never, never, never>;
    asList: import("../Operation").Operation<"value", never, never, never, never>;
    asMap: import("../Operation").Operation<"value", never, never, never, never>;
    asNumber: import("../Operation").Operation<"value", never, never, never, never>;
    asObject: import("../Operation").Operation<"value", never, never, never, never>;
    asText: import("../Operation").Operation<"value", never, never, never, never>;
    asTuple: import("../Operation").Operation<"value", never, never, never, never>;
};
