import { Operations } from '../Operation';
export declare const DateOperations: Operations;
export declare const DateOps: {
    create: import("../Operation").Operation<never, never, never, never, never>;
    now: import("../Operation").Operation<never, never, never, never, never>;
    today: import("../Operation").Operation<never, never, never, never, never>;
    tomorrow: import("../Operation").Operation<never, never, never, never, never>;
    yesterday: import("../Operation").Operation<never, never, never, never, never>;
    maybe: import("../Operation").Operation<"value", never, never, never, never>;
    parse: import("../Operation").Operation<"value", "parseAsUTC", never, "value" | "parseAsUTC", "value" | "parseAsUTC">;
    fromText: import("../Operation").Operation<"value", "parseAsUTC", never, "value" | "parseAsUTC", "value" | "parseAsUTC">;
    fromTimestamp: import("../Operation").Operation<"value", never, never, never, never>;
    fromTimestampSeconds: import("../Operation").Operation<"value", never, never, never, never>;
    min: import("../Operation").Operation<"value" | "test", never, never, never, never>;
    max: import("../Operation").Operation<"value" | "test", never, never, never, never>;
    get: import("../Operation").Operation<"value" | "property", never, never, never, never>;
    set: import("../Operation").Operation<"value" | "property" | "set", never, never, never, never>;
    add: import("../Operation").Operation<"value" | "unit", "amount", never, "value" | "unit" | "amount", "value" | "unit" | "amount">;
    sub: import("../Operation").Operation<"value" | "unit", "amount", never, "value" | "unit" | "amount", "value" | "unit" | "amount">;
    startOf: import("../Operation").Operation<"value" | "unit", never, never, never, never>;
    endOf: import("../Operation").Operation<"value" | "unit", "inclusive", never, "value" | "unit" | "inclusive", "value" | "unit" | "inclusive">;
    daysInMonth: import("../Operation").Operation<"value", never, never, never, never>;
    daysInYear: import("../Operation").Operation<"value", never, never, never, never>;
    weeksInYear: import("../Operation").Operation<"value", never, never, never, never>;
    copy: import("../Operation").Operation<"value", never, never, never, never>;
    cmp: import("../Operation").Operation<"value" | "test", "unit", never, "value" | "test" | "unit", "value" | "test" | "unit">;
    diff: import("../Operation").Operation<"value" | "test", "unit" | "absolute" | "adjust", never, "value" | "test" | "unit" | "absolute" | "adjust", "value" | "test" | "unit" | "absolute" | "adjust">;
    timezoneOffset: import("../Operation").Operation<"value", never, never, never, never>;
    toText: import("../Operation").Operation<"value" | "format", never, never, never, never>;
    toISOText: import("../Operation").Operation<"value", never, never, never, never>;
    isValid: import("../Operation").Operation<"value", never, never, never, never>;
    isEqual: import("../Operation").Operation<"value" | "test", "unit", never, "value" | "test" | "unit", "value" | "test" | "unit">;
    isBefore: import("../Operation").Operation<"value" | "test", "unit", never, "value" | "test" | "unit", "value" | "test" | "unit">;
    isBeforeOrEqual: import("../Operation").Operation<"value" | "test", "unit", never, "value" | "test" | "unit", "value" | "test" | "unit">;
    isAfter: import("../Operation").Operation<"value" | "test", "unit", never, "value" | "test" | "unit", "value" | "test" | "unit">;
    isAfterOrEqual: import("../Operation").Operation<"value" | "test", "unit", never, "value" | "test" | "unit", "value" | "test" | "unit">;
    isBetween: import("../Operation").Operation<"value" | "start" | "end", "unit" | "startInclusive" | "endInclusive", never, "value" | "unit" | "start" | "end" | "startInclusive" | "endInclusive", "value" | "unit" | "start" | "end" | "startInclusive" | "endInclusive">;
    isStartOf: import("../Operation").Operation<"value" | "unit", never, never, never, never>;
    isEndOf: import("../Operation").Operation<"value" | "unit", "inclusive", never, "value" | "unit" | "inclusive", "value" | "unit" | "inclusive">;
    isDST: import("../Operation").Operation<"value", never, never, never, never>;
    isLeapYear: import("../Operation").Operation<"value", never, never, never, never>;
    asAny: import("../Operation").Operation<"value", never, never, never, never>;
    asBoolean: import("../Operation").Operation<"value", never, never, never, never>;
    asDate: import("../Operation").Operation<"value", never, never, never, never>;
    asList: import("../Operation").Operation<"value", never, never, never, never>;
    asMap: import("../Operation").Operation<"value", never, never, never, never>;
    asNumber: import("../Operation").Operation<"value", never, never, never, never>;
    asObject: import("../Operation").Operation<"value", never, never, never, never>;
    asText: import("../Operation").Operation<"value", never, never, never, never>;
    asTuple: import("../Operation").Operation<"value", never, never, never, never>;
};
