import { Operations } from '../Operation';
import { Computeds } from '../Computed';
export declare const DateOperations: Operations;
export declare const DateComputeds: Computeds;
export declare const DateOps: {
    create: import("../Operation").OperationResolved<never, never, never, never, never>;
    now: import("../Operation").OperationResolved<never, never, never, never, never>;
    today: import("../Operation").OperationResolved<never, never, never, never, never>;
    tomorrow: import("../Operation").OperationResolved<never, never, never, never, never>;
    yesterday: import("../Operation").OperationResolved<never, never, never, never, never>;
    maybe: import("../Operation").OperationResolved<"value", never, never, never, never>;
    parse: import("../Operation").OperationResolved<"value", "parseAsUTC", never, never, never>;
    fromText: import("../Operation").OperationResolved<"value", "parseAsUTC", never, never, never>;
    fromTimestamp: import("../Operation").OperationResolved<"value", never, never, never, never>;
    fromTimestampSeconds: import("../Operation").OperationResolved<"value", never, never, never, never>;
    min: import("../Operation").OperationResolved<"value" | "test", never, never, never, never>;
    max: import("../Operation").OperationResolved<"value" | "test", never, never, never, never>;
    get: import("../Operation").OperationResolved<"value" | "property", never, never, never, never>;
    set: import("../Operation").OperationResolved<"set" | "value" | "property", never, never, never, never>;
    add: import("../Operation").OperationResolved<"value" | "unit", "amount", never, never, never>;
    sub: import("../Operation").OperationResolved<"value" | "unit", "amount", never, never, never>;
    startOf: import("../Operation").OperationResolved<"value" | "unit", never, never, never, never>;
    endOf: import("../Operation").OperationResolved<"value" | "unit", "inclusive", never, never, never>;
    daysInMonth: import("../Operation").OperationResolved<"value", never, never, never, never>;
    daysInYear: import("../Operation").OperationResolved<"value", never, never, never, never>;
    weeksInYear: import("../Operation").OperationResolved<"value", never, never, never, never>;
    copy: import("../Operation").OperationResolved<"value", never, never, never, never>;
    cmp: import("../Operation").OperationResolved<"value" | "test", "unit", never, never, never>;
    diff: import("../Operation").OperationResolved<"value" | "test", "unit" | "absolute" | "adjust", never, never, never>;
    timezoneOffset: import("../Operation").OperationResolved<"value", never, never, never, never>;
    toText: import("../Operation").OperationResolved<"value" | "format", never, never, never, never>;
    toISOText: import("../Operation").OperationResolved<"value", never, never, never, never>;
    isValid: import("../Operation").OperationResolved<"value", never, never, never, never>;
    isEqual: import("../Operation").OperationResolved<"value" | "test", "unit", never, never, never>;
    isBefore: import("../Operation").OperationResolved<"value" | "test", "unit", never, never, never>;
    isBeforeOrEqual: import("../Operation").OperationResolved<"value" | "test", "unit", never, never, never>;
    isAfter: import("../Operation").OperationResolved<"value" | "test", "unit", never, never, never>;
    isAfterOrEqual: import("../Operation").OperationResolved<"value" | "test", "unit", never, never, never>;
    isBetween: import("../Operation").OperationResolved<"value" | "start" | "end", "unit" | "startInclusive" | "endInclusive", never, never, never>;
    isStartOf: import("../Operation").OperationResolved<"value" | "unit", never, never, never, never>;
    isEndOf: import("../Operation").OperationResolved<"value" | "unit", "inclusive", never, never, never>;
    isDST: import("../Operation").OperationResolved<"value", never, never, never, never>;
    isLeapYear: import("../Operation").OperationResolved<"value", never, never, never, never>;
    asAny: import("../Operation").OperationResolved<"value", never, never, never, never>;
    asBoolean: import("../Operation").OperationResolved<"value", never, never, never, never>;
    asColor: import("../Operation").OperationResolved<"value", never, never, never, never>;
    asDate: import("../Operation").OperationResolved<"value", never, never, never, never>;
    asList: import("../Operation").OperationResolved<"value", never, never, never, never>;
    asMap: import("../Operation").OperationResolved<"value", never, never, never, never>;
    asNumber: import("../Operation").OperationResolved<"value", never, never, never, never>;
    asObject: import("../Operation").OperationResolved<"value", never, never, never, never>;
    asText: import("../Operation").OperationResolved<"value", never, never, never, never>;
    asTuple: import("../Operation").OperationResolved<"value", never, never, never, never>;
    asSet: import("../Operation").OperationResolved<"value", never, never, never, never>;
};
