import { Type, TypeSub, TypeCompatibleOptions, TypeDescribeProvider, TypeMap, TypeProvider, TypeChild, TypeMapFor } from '../Type';
import { Operations } from '../Operation';
import { Expression } from '../Expression';
import { DefinitionProvider } from '../DefinitionProvider';
import { Traverser, TraverseStep } from '../Traverser';
import { Computeds } from '../Computed';
import { GenericType } from './Generic';
import { FunctionExpression } from '../exprs/Function';
import { ObjectType } from './Object';
export declare type FunctionParams = Record<string, any>;
export declare type FunctionTypeProvider<T, P extends FunctionParams> = Type<T> | ((params: Partial<TypeMapFor<P>>, types: TypeProvider) => Type<T>);
export interface FunctionOptions<P extends FunctionParams = any, R = any> {
    params: {
        [K in keyof P]: FunctionTypeProvider<P[K], P>;
    };
    returns?: FunctionTypeProvider<R, P>;
}
export declare type FunctionInterface<P extends FunctionParams = any, R = any> = (params: P) => R;
export declare type FunctionValue<P extends FunctionParams = any, R = any> = FunctionExpression | FunctionInterface<P, R> | string;
export declare class FunctionType<P extends FunctionParams = any, R = any> extends Type<FunctionValue<P, R>, FunctionOptions<P, R>> {
    static STEP_RETURNS: string;
    static CHILD_RETURN: string;
    static id: string;
    static operations: Operations;
    static computeds: Computeds;
    static baseType: FunctionType<any, any>;
    static decode(data: any[], types: TypeProvider): FunctionType;
    static encode(type: FunctionType): any;
    static describePriority: number;
    static describe(data: any, describer: TypeDescribeProvider, cache: Map<any, Type>): Type | undefined;
    static registered: boolean;
    static register(): void;
    provider: TypeProvider;
    constructor(options: FunctionOptions<P, R>, provider: TypeProvider);
    getParamTypesType(inputTypes?: Partial<TypeMapFor<P>>): ObjectType<P>;
    getParamTypes(inputTypes?: Partial<TypeMapFor<P>>): TypeMapFor<P>;
    getParamType<K extends keyof P>(param: K, inputTypes?: Partial<TypeMapFor<P>>): Type<P[K]> | undefined;
    getReturnType(inputTypes?: Partial<TypeMapFor<P>>): Type<R> | undefined;
    getProvided<T>(provider: FunctionTypeProvider<T, P>, inputTypes?: Partial<TypeMapFor<P>>): Type<T>;
    getProvided<T>(provider: FunctionTypeProvider<T, P> | undefined, inputTypes?: Partial<TypeMapFor<P>>): Type<T> | undefined;
    getTypeFromPath(path: TypeChild[], inputTypes?: TypeMap): Type | undefined;
    getOverloaded(inputTypes?: TypeMap): FunctionType;
    getResolvedType(type: GenericType, inputTypes?: Partial<TypeMapFor<P>>): Type | undefined;
    getId(): string;
    getOperations(): {};
    merge(type: FunctionType): void;
    getSubType(expr: Expression, def: DefinitionProvider, context: Type): Type | undefined;
    getSubTypes(def: DefinitionProvider): TypeSub[];
    getChildType(name: TypeChild): Type | undefined;
    getChildTypes(): TypeChild[];
    getExactType(value: any): Type;
    getSimplifiedType(): Type;
    protected isDeepCompatible(other: Type, options: TypeCompatibleOptions): boolean;
    isOptional(): boolean;
    isSimple(): boolean;
    traverse<A>(traverse: Traverser<Type, A>): A;
    getTypeFromStep(step: TraverseStep): Type | undefined;
    setParent(parent?: Type): void;
    removeDescribedRestrictions(): void;
    getCreateExpression(): Expression;
    getValidateExpression(): Expression;
    getCompareExpression(): Expression;
    isValid(value: any): value is FunctionValue<P, R>;
    normalize(value: any): any;
    newInstance(): FunctionType;
    clone(): FunctionType;
    encode(): any;
    create(): FunctionValue;
    random(rnd: (a: number, b: number, whole: boolean) => number): any;
    fromJsonArguments(json: any): any;
    toJsonArguments(args: any): any;
    fromJson(json: any): FunctionValue<P, R>;
    toJson(value: FunctionValue<P, R>): any;
}
