import { Type, TypeSub, TypeCompatibleOptions, TypeDescribeProvider, TypeMap, TypeProvider, TypeChild } from '../Type';
import { Operations } from '../Operation';
import { Expression } from '../Expression';
import { DefinitionProvider } from '../DefinitionProvider';
import { Traverser, TraverseStep } from '../Traverser';
import { Computeds } from '../Computed';
import { GenericType } from './Generic';
export declare type FunctionTypeProvider = Type | ((params: TypeMap) => Type);
export interface FunctionOptions {
    params: Record<string, FunctionTypeProvider>;
    returns?: FunctionTypeProvider;
}
export declare class FunctionType extends Type<FunctionOptions> {
    static STEP_RETURNS: string;
    static CHILD_RETURN: string;
    static id: string;
    static operations: Operations;
    static computeds: Computeds;
    static baseType: FunctionType;
    static decode(data: any[], types: TypeProvider): FunctionType;
    static encode(type: FunctionType): any;
    static describePriority: number;
    static describe(data: any, describer: TypeDescribeProvider, cache: Map<any, Type>): Type | null;
    static registered: boolean;
    static register(): void;
    getParamTypes(inputTypes?: TypeMap): TypeMap;
    getReturnType(inputTypes?: TypeMap): Type;
    getTypeFromPath(path: TypeChild[], inputTypes?: TypeMap): Type | null;
    getOverloaded(inputTypes?: TypeMap): FunctionType;
    getResolvedType(type: GenericType, inputTypes?: TypeMap): Type;
    getId(): string;
    getOperations(): {};
    merge(type: FunctionType): void;
    getSubType(expr: Expression, def: DefinitionProvider, context: Type): Type | null;
    getSubTypes(def: DefinitionProvider): TypeSub[];
    getChildType(name: TypeChild): Type | null;
    getChildTypes(): TypeChild[];
    getExactType(value: any): Type;
    getSimplifiedType(): Type;
    protected isDeepCompatible(other: Type, options: TypeCompatibleOptions): boolean;
    isOptional(): boolean;
    isSimple(): boolean;
    traverse<R>(traverse: Traverser<Type, R>): R;
    getTypeFromStep(step: TraverseStep): Type | null;
    setParent(parent?: Type): void;
    removeDescribedRestrictions(): void;
    getCreateExpression(): Expression;
    getValidateExpression(): Expression;
    getCompareExpression(): Expression;
    isValid(value: any): boolean;
    normalize(value: any): any;
    newInstance(): FunctionType;
    clone(): FunctionType;
    encode(): any;
    create(): null;
    random(rnd: (a: number, b: number, whole: boolean) => number): any;
    fromJson(json: null): null;
    toJson(value: null): null;
}
