export declare const ID: {
    Any: string;
    Boolean: string;
    Color: string;
    Date: string;
    Enum: string;
    Function: string;
    List: string;
    Many: string;
    Not: string;
    Map: string;
    Null: string;
    Number: string;
    Object: string;
    Optional: string;
    Relation: string;
    Set: string;
    Text: string;
    Tuple: string;
    Delimiter: string;
};
