import { Type, TypeProvider, TypeInput, TypeDescribeProvider, TypeSub, TypeCompatibleOptions, TypeChild } from '../Type';
import { Expression } from '../Expression';
import { DefinitionProvider } from '../DefinitionProvider';
import { Traverser, TraverseStep } from '../Traverser';
export interface ListOptions<I = any> {
    item: Type<I>;
    min?: number;
    max?: number;
}
export declare class ListType<I = any> extends Type<I[], ListOptions<I>> {
    static STEP_ITEM: string;
    static CHILD_ITEM: string;
    static id: string;
    static operations: import("..").Operations;
    static computeds: import("..").Computeds;
    static baseType: ListType<any>;
    static decode(data: any[], types: TypeProvider): ListType;
    static encode(type: ListType): any;
    static describePriority: number;
    static describe(data: any, describer: TypeDescribeProvider, cache: Map<any, Type>): Type | undefined;
    static registered: boolean;
    static register(): void;
    static forItem(itemOrClass: TypeInput): ListType<any>;
    getId(): string;
    getOperations(): Record<string, import("..").OperationGeneric>;
    merge(type: ListType): void;
    getSubType(expr: Expression, def: DefinitionProvider, context: Type): Type | undefined;
    getSubTypes(def: DefinitionProvider): TypeSub[];
    getChildType(name: TypeChild): Type | undefined;
    getChildTypes(): TypeChild[];
    getExactType(value: any): Type;
    getSimplifiedType(): Type;
    protected isDeepCompatible(other: Type, options: TypeCompatibleOptions): boolean;
    isOptional(): boolean;
    isSimple(): boolean;
    traverse<R>(traverse: Traverser<Type, R>): R;
    getTypeFromStep(step: TraverseStep): Type | undefined;
    setParent(parent?: Type): void;
    removeDescribedRestrictions(): void;
    getCreateExpression(): Expression;
    getValidateExpression(): Expression;
    getCompareExpression(): Expression;
    getValueChangeExpression(newValue: Expression, from?: TraverseStep, to?: TraverseStep): Expression;
    isValid(value: any): value is I[];
    normalize(value: any): any;
    newInstance(): ListType;
    clone(): ListType;
    encode(): any;
    create(): I[];
    random(rnd: (a: number, b: number, whole: boolean) => number): I[];
    fromJson(json: any[] | null): any;
    toJson(value: I[] | null): any;
}
