import { Type, TypeProvider, TypeInput, TypeDescribeProvider, TypeSub, TypeCompatibleOptions, TypeChild } from '../Type';
import { Expression } from '../Expression';
import { DefinitionProvider } from '../DefinitionProvider';
import { Traverser, TraverseStep } from '../Traverser';
export interface SetOptions<V> {
    value: Type<V>;
}
export declare class SetType<V = any> extends Type<Set<V>, SetOptions<V>> {
    static STEP_VALUE: string;
    static CHILD_VALUE: string;
    static id: string;
    static operations: import("..").Operations;
    static computeds: import("..").Computeds;
    static baseType: SetType<any>;
    static decode(data: any[], types: TypeProvider): SetType;
    static encode(type: SetType): any;
    static describePriority: number;
    static describe(data: any, describer: TypeDescribeProvider, cache: Map<any, Type>): Type | undefined;
    static registered: boolean;
    static register(): void;
    static forItem(valueOrClass: TypeInput): SetType<any>;
    getId(): string;
    getOperations(): Record<string, import("..").OperationGeneric>;
    merge(type: SetType): void;
    getSubType(expr: Expression, def: DefinitionProvider, context: Type): Type | undefined;
    getSubTypes(def: DefinitionProvider): TypeSub[];
    getChildType(name: TypeChild): Type | undefined;
    getChildTypes(): TypeChild[];
    getExactType(value: any): Type;
    getSimplifiedType(): Type;
    protected isDeepCompatible(other: Type, options: TypeCompatibleOptions): boolean;
    isOptional(): boolean;
    isSimple(): boolean;
    traverse<R>(traverse: Traverser<Type, R>): R;
    getTypeFromStep(step: TraverseStep): Type | undefined;
    setParent(parent?: Type): void;
    removeDescribedRestrictions(): void;
    getCreateExpression(): Expression;
    getValidateExpression(): Expression;
    getCompareExpression(): Expression;
    getValueChangeExpression(newValue: Expression, from?: TraverseStep, to?: TraverseStep): Expression;
    isValid(test: any): test is Set<V>;
    normalize(test: any): any;
    newInstance(): SetType<V>;
    clone(): SetType<V>;
    encode(): any;
    create(): Set<V>;
    random(rnd: (a: number, b: number, whole: boolean) => number): Set<V>;
    fromJson(json: Array<V>): Set<V>;
    toJson(set: Set<V>): Array<V>;
}
