import { Type, TypeProvider, TypeDescribeProvider, TypeInput, TypeSub, TypeCompatibleOptions, TypeChild } from '../Type';
import { Expression } from '../Expression';
import { DefinitionProvider } from '../DefinitionProvider';
import { Traverser, TraverseStep } from '../Traverser';
export declare type TupleOptions<E extends any[]> = unknown extends E ? Type[] : {
    [K in keyof E]: Type<E[K]>;
};
export declare class TupleType<E extends any[] = any> extends Type<E, TupleOptions<E>> {
    static id: string;
    static operations: import("..").Operations;
    static computeds: import("..").Computeds;
    static baseType: TupleType<unknown[]>;
    static decode(data: any[], types: TypeProvider): TupleType;
    static encode(type: TupleType): any;
    static describePriority: number;
    static describe(data: any, describer: TypeDescribeProvider, cache: Map<any, Type>): Type | null;
    static registered: boolean;
    static register(): void;
    static forItem(types: TypeInput[]): TupleType<any[]>;
    getId(): string;
    getOperations(): Record<string, import("..").OperationGeneric>;
    merge(type: Type<E, TupleOptions<E>>): void;
    getSubType(expr: Expression, def: DefinitionProvider, context: Type): Type | null;
    getSubTypes(def: DefinitionProvider): TypeSub[];
    getChildType(name: TypeChild): Type | null;
    getChildTypes(): TypeChild[];
    getExactType(value: any): Type;
    getSimplifiedType(): Type;
    getCreateExpression(): Expression;
    getValidateExpression(): Expression;
    getCompareExpression(): Expression;
    getValueChangeExpression(newValue: Expression, from?: TraverseStep, to?: TraverseStep): Expression;
    protected isDeepCompatible(other: Type, options: TypeCompatibleOptions): boolean;
    isOptional(): boolean;
    isSimple(): boolean;
    traverse<R>(traverse: Traverser<Type, R>): R;
    getTypeFromStep(step: TraverseStep): Type | null;
    setParent(parent?: Type): void;
    removeDescribedRestrictions(): void;
    isValid(value: any): value is E;
    normalize(value: any): any;
    newInstance(): TupleType<E>;
    clone(): TupleType<E>;
    encode(): any;
    create(): E;
    random(rnd: (a: number, b: number, whole: boolean) => number): any;
    fromJson(json: any[]): E;
    toJson(value: E): any[];
}
