import { Expression, ExpressionProvider } from '../Expression';
import { DefinitionProvider } from '../DefinitionProvider';
import { Type } from '../Type';
import { Traverser, TraverseStep } from '../Traverser';
import { ValidationHandler } from '../Validate';
import { FlowType } from "../FlowType";
export declare class DoExpression extends Expression {
    static STEP_CONDITION: string;
    static STEP_BODY: string;
    static MAX_ITERATIONS: number;
    static id: string;
    static decode(data: any[], exprs: ExpressionProvider): DoExpression;
    static encode(expr: DoExpression): any;
    condition: Expression;
    body: Expression;
    maxIterations: number;
    constructor(condition: Expression, body: Expression, maxIterations?: number);
    getId(): string;
    getComplexity(def: DefinitionProvider, context: Type): number;
    isDynamic(): boolean;
    getScope(): undefined;
    encode(): any;
    clone(): Expression;
    getType(def: DefinitionProvider, context: Type): Type | undefined;
    traverse<R>(traverse: Traverser<Expression, R>): R;
    getExpressionFromStep(steps: TraverseStep[]): [number, Expression] | undefined;
    setParent(parent?: Expression): void;
    validate(def: DefinitionProvider, context: Type, handler: ValidationHandler): void;
    mutates(def: DefinitionProvider, arg: string, directly?: boolean): boolean;
    isValidFlow(def: DefinitionProvider, type: FlowType, child?: Expression): boolean;
    do(body: Expression, condition?: Expression): DoExpression;
    while(condition: Expression): DoExpression;
    withMax(iterations: number): this;
}
