import { Expression, ExpressionProvider, ExpressionValue } from '../Expression';
import { NumberType } from '../types/Number';
import { DefinitionProvider } from '../DefinitionProvider';
import { Type } from '../Type';
import { Traverser, TraverseStep } from '../Traverser';
import { ValidationHandler } from '../Validate';
import { FlowType } from "../FlowType";
export declare class ForExpression extends Expression {
    static STEP_START: string;
    static STEP_END: string;
    static STEP_BODY: string;
    static STEP_BY: string;
    static MAX_ITERATIONS: number;
    static id: string;
    static decode(data: any[], exprs: ExpressionProvider): ForExpression;
    static encode(expr: ForExpression): any;
    variable: string;
    start: Expression;
    end: Expression;
    body: Expression;
    by: Expression;
    maxIterations: number;
    constructor(variable: string, start: Expression, end: Expression, body: Expression, by: Expression, maxIterations?: number);
    getId(): string;
    getComplexity(def: DefinitionProvider, context: Type): number;
    isDynamic(): boolean;
    getScope(): {
        [x: string]: NumberType;
    };
    encode(): any;
    clone(): Expression;
    getType(def: DefinitionProvider, original: Type): Type | null;
    getContextFor(steps: TraverseStep[], def: DefinitionProvider, context: Type, thisType?: Type): Type;
    traverse<R>(traverse: Traverser<Expression, R>): R;
    getExpressionFromStep(steps: TraverseStep[]): [number, Expression] | null;
    setParent(parent?: Expression): void;
    validate(def: DefinitionProvider, context: Type, handler: ValidationHandler): void;
    mutates(def: DefinitionProvider, arg: string, directly?: boolean): boolean;
    isValidFlow(def: DefinitionProvider, type: FlowType, child?: Expression): boolean;
    loop(variable: string, start: ExpressionValue, end: ExpressionValue, body?: Expression, by?: ExpressionValue, maxIterations?: number): ForExpression;
    startAt(start: ExpressionValue): ForExpression;
    endAt(end: ExpressionValue): ForExpression;
    inc(by: ExpressionValue): ForExpression;
    run(expr: Expression): ForExpression;
    withVariable(name: string): this;
    withMax(iterations: number): this;
}
