import { Expression, ExpressionProvider, ExpressionValue } from '../Expression';
import { DefinitionProvider } from '../DefinitionProvider';
import { Operation } from '../Operation';
import { Type } from '../Type';
import { Traverser, TraverseStep } from '../Traverser';
import { ValidationHandler } from '../Validate';
export declare class SwitchExpression extends Expression {
    static STEP_VALUE: string;
    static STEP_CASES: string;
    static STEP_CASE: string;
    static STEP_RESULT: string;
    static STEP_DEFAULT: string;
    static id: string;
    static decode(data: any[], exprs: ExpressionProvider): SwitchExpression;
    static encode(expr: SwitchExpression): any;
    value: Expression;
    op: string;
    cases: [Expression[], Expression][];
    defaultCase: Expression;
    constructor(value: Expression, op: string, cases: [Expression[], Expression][], defaultCase: Expression);
    getId(): string;
    getComplexity(def: DefinitionProvider): number;
    getScope(): null;
    encode(): any;
    clone(): Expression;
    getType(def: DefinitionProvider, context: Type): Type | null;
    traverse<R>(traverse: Traverser<Expression, R>): R;
    getExpressionFromStep(steps: TraverseStep[]): [number, Expression] | null;
    setParent(parent?: Expression): void;
    validate(def: DefinitionProvider, context: Type, handler: ValidationHandler): void;
    val(value: ExpressionValue, op?: Operation): SwitchExpression;
    case(testValue: ExpressionValue): SwitchExpression;
    than(bodyValue: ExpressionValue): SwitchExpression;
    default(body: ExpressionValue): this;
}
